@apiUrl = http://localhost:{{$dotenv PORT}}

POST {{apiUrl}}/users HTTP/1.1
Content-Type: application/json

{
    "email": "e1231lld2312300@gmail.com",
    "nome": "Dave1223R123meawdl",
    "password": "12345678"
}